
project_id = "jxiiletuljcxulpltdss"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[graphql]
enabled = true
port = 54329

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54325
image_transformation_enabled = true

[auth]
enabled = true
port = 54324
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://jxiiletuljcxulpltdss.supabase.co/auth/v1/callback"]
jwt_expiry = 3600

[edge_functions]
enabled = true

[functions.paystack-webhook]
verify_jwt = false

[db]
port = 54322
shadow_port = 54320
