// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jxiiletuljcxulpltdss.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp4aWlsZXR1bGpjeHVscGx0ZHNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2OTM0NzUsImV4cCI6MjA2NDI2OTQ3NX0.fn6OD7MhP9rGLoD3z8M6KJX5C01q8UxN8kv3omDAbWc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);